//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JobTitleResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobTitleResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms.Enums.JobTitleResx", typeof(JobTitleResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner/Partner/Principal/GM.
        /// </summary>
        public static string JT01 {
            get {
                return ResourceManager.GetString("JT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President/CEO.
        /// </summary>
        public static string JT02 {
            get {
                return ResourceManager.GetString("JT02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFO/VP of Finance.
        /// </summary>
        public static string JT03 {
            get {
                return ResourceManager.GetString("JT03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director/Senior Manager.
        /// </summary>
        public static string JT04 {
            get {
                return ResourceManager.GetString("JT04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Manager/Controller.
        /// </summary>
        public static string JT05 {
            get {
                return ResourceManager.GetString("JT05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string JT15 {
            get {
                return ResourceManager.GetString("JT15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Job Title.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
    }
}
