//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.SC.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.SC.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OfferBannerMY {
            get {
                object obj = ResourceManager.GetObject("OfferBannerMY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OfferBannerSG {
            get {
                object obj = ResourceManager.GetObject("OfferBannerSG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 style=&quot;font-size: 2em; font-weight: bold;&quot;&gt;Terms And Conditions&lt;/h1&gt;
        ///&lt;h3 style=&quot;font-size: 1.5em; font-weight: bold;&quot;&gt;IMPORTANT NOTES&lt;/h3&gt;
        ///&lt;ol&gt;
        ///&lt;li style=&quot;list-style-type: decimal;&quot;&gt;Your company/business/partnership (“Company”) is receiving this notice about the Business Instalment Loan (“Loan”)/ BizFinancing-I (“Financing”) offered by Standard Chartered Bank Malaysia Berhad and Standard Chartered Saadiq Berhad respectively (each, the “Bank”) based solely on your Company’s financial and transactional [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TermsAndConditionsMY {
            get {
                return ResourceManager.GetString("TermsAndConditionsMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 style=&quot;font-size: 2em; font-weight: bold;&quot;&gt;Terms And Conditions&lt;/h1&gt;
        ///&lt;h3 style=&quot;font-size: 1.5em; font-weight: bold;&quot;&gt;IMPORTANT NOTES&lt;/h3&gt;
        ///&lt;ol&gt;
        ///&lt;li style=&quot;list-style-type: decimal;&quot;&gt;Your company/business/partnership (“Company”) is receiving this notice about the Standard Chartered Bank (Singapore) Limited (“Bank”) Business Instalment Loan (“Loan”) based solely on your Company’s financial and transactional information available on this platform. Receipt of this notice should therefore not be construed [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TermsAndConditionsSG {
            get {
                return ResourceManager.GetString("TermsAndConditionsSG", resourceCulture);
            }
        }
    }
}
