namespace Sage.CA.SBS.ERP.Sage300.SC.AccpacSC1100.Pages
{
    partial class SCPageCashFlowSummary
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SCPageCashFlowSummary));
            Telerik.WinControls.UI.GridViewCheckBoxColumn gridViewCheckBoxColumn1 = new Telerik.WinControls.UI.GridViewCheckBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn2 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn3 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn4 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn5 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn6 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn7 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn8 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition1 = new Telerik.WinControls.UI.TableViewDefinition();
            this.grdCashFlowSummary = new Telerik.WinControls.UI.RadGridView();
            this.btnPrint = new Telerik.WinControls.UI.RadDropDownButton();
            this.btnPrint_Summary = new Telerik.WinControls.UI.RadMenuItem();
            this.btnPrint_CashAndBank = new Telerik.WinControls.UI.RadMenuItem();
            this.btnPrint_CashFlowEntries = new Telerik.WinControls.UI.RadMenuItem();
            this.grpCFEntries = new Telerik.WinControls.UI.RadGroupBox();
            this.vlSCTRAN = new AxAccpacFldList.AxAccpacViewList();
            ((System.ComponentModel.ISupportInitialize)(this.grdCashFlowSummary)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdCashFlowSummary.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnPrint)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grpCFEntries)).BeginInit();
            this.grpCFEntries.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.vlSCTRAN)).BeginInit();
            this.SuspendLayout();
            // 
            // grdCashFlowSummary
            // 
            resources.ApplyResources(this.grdCashFlowSummary, "grdCashFlowSummary");
            this.grdCashFlowSummary.BackColor = System.Drawing.SystemColors.Control;
            this.grdCashFlowSummary.Cursor = System.Windows.Forms.Cursors.Default;
            this.grdCashFlowSummary.ForeColor = System.Drawing.SystemColors.ControlText;
            // 
            // 
            // 
            this.grdCashFlowSummary.MasterTemplate.AllowAddNewRow = false;
            this.grdCashFlowSummary.MasterTemplate.AllowColumnReorder = false;
            this.grdCashFlowSummary.MasterTemplate.AllowRowResize = false;
            this.grdCashFlowSummary.MasterTemplate.AutoGenerateColumns = false;
            this.grdCashFlowSummary.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill;
            gridViewCheckBoxColumn1.EnableExpressionEditor = false;
            gridViewCheckBoxColumn1.FieldName = "Important";
            resources.ApplyResources(gridViewCheckBoxColumn1, "gridViewCheckBoxColumn1");
            gridViewCheckBoxColumn1.IsAutoGenerated = true;
            gridViewCheckBoxColumn1.IsVisible = false;
            gridViewCheckBoxColumn1.MinWidth = 20;
            gridViewCheckBoxColumn1.Name = "Important";
            gridViewCheckBoxColumn1.Width = 61;
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "Description";
            resources.ApplyResources(gridViewTextBoxColumn1, "gridViewTextBoxColumn1");
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.MinWidth = 120;
            gridViewTextBoxColumn1.Name = "Description";
            gridViewTextBoxColumn1.Width = 165;
            gridViewDecimalColumn1.EnableExpressionEditor = false;
            gridViewDecimalColumn1.FieldName = "AmountPeriod0";
            resources.ApplyResources(gridViewDecimalColumn1, "gridViewDecimalColumn1");
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.Name = "AmountPeriod0";
            gridViewDecimalColumn1.Width = 80;
            gridViewDecimalColumn2.EnableExpressionEditor = false;
            gridViewDecimalColumn2.FieldName = "AmountPeriod1";
            resources.ApplyResources(gridViewDecimalColumn2, "gridViewDecimalColumn2");
            gridViewDecimalColumn2.IsAutoGenerated = true;
            gridViewDecimalColumn2.Name = "AmountPeriod1";
            gridViewDecimalColumn2.Width = 80;
            gridViewDecimalColumn3.EnableExpressionEditor = false;
            gridViewDecimalColumn3.FieldName = "AmountPeriod2";
            resources.ApplyResources(gridViewDecimalColumn3, "gridViewDecimalColumn3");
            gridViewDecimalColumn3.IsAutoGenerated = true;
            gridViewDecimalColumn3.Name = "AmountPeriod2";
            gridViewDecimalColumn3.Width = 81;
            gridViewDecimalColumn4.EnableExpressionEditor = false;
            gridViewDecimalColumn4.FieldName = "AmountPeriod3";
            resources.ApplyResources(gridViewDecimalColumn4, "gridViewDecimalColumn4");
            gridViewDecimalColumn4.IsAutoGenerated = true;
            gridViewDecimalColumn4.Name = "AmountPeriod3";
            gridViewDecimalColumn4.Width = 81;
            gridViewDecimalColumn5.EnableExpressionEditor = false;
            gridViewDecimalColumn5.FieldName = "AmountPeriod4";
            resources.ApplyResources(gridViewDecimalColumn5, "gridViewDecimalColumn5");
            gridViewDecimalColumn5.IsAutoGenerated = true;
            gridViewDecimalColumn5.Name = "AmountPeriod4";
            gridViewDecimalColumn5.Width = 81;
            gridViewDecimalColumn6.EnableExpressionEditor = false;
            gridViewDecimalColumn6.FieldName = "AmountPeriod5";
            resources.ApplyResources(gridViewDecimalColumn6, "gridViewDecimalColumn6");
            gridViewDecimalColumn6.IsAutoGenerated = true;
            gridViewDecimalColumn6.Name = "AmountPeriod5";
            gridViewDecimalColumn6.Width = 81;
            gridViewDecimalColumn7.EnableExpressionEditor = false;
            gridViewDecimalColumn7.FieldName = "AmountPeriod6";
            resources.ApplyResources(gridViewDecimalColumn7, "gridViewDecimalColumn7");
            gridViewDecimalColumn7.IsAutoGenerated = true;
            gridViewDecimalColumn7.Name = "AmountPeriod6";
            gridViewDecimalColumn7.Width = 81;
            gridViewDecimalColumn8.EnableExpressionEditor = false;
            gridViewDecimalColumn8.FieldName = "AmountTotal";
            resources.ApplyResources(gridViewDecimalColumn8, "gridViewDecimalColumn8");
            gridViewDecimalColumn8.IsAutoGenerated = true;
            gridViewDecimalColumn8.Name = "AmountTotal";
            gridViewDecimalColumn8.Width = 71;
            this.grdCashFlowSummary.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewCheckBoxColumn1,
            gridViewTextBoxColumn1,
            gridViewDecimalColumn1,
            gridViewDecimalColumn2,
            gridViewDecimalColumn3,
            gridViewDecimalColumn4,
            gridViewDecimalColumn5,
            gridViewDecimalColumn6,
            gridViewDecimalColumn7,
            gridViewDecimalColumn8});
            this.grdCashFlowSummary.MasterTemplate.EnableAlternatingRowColor = true;
            this.grdCashFlowSummary.MasterTemplate.EnableGrouping = false;
            this.grdCashFlowSummary.MasterTemplate.EnableSorting = false;
            this.grdCashFlowSummary.MasterTemplate.ShowRowHeaderColumn = false;
            this.grdCashFlowSummary.MasterTemplate.ViewDefinition = tableViewDefinition1;
            this.grdCashFlowSummary.Name = "grdCashFlowSummary";
            this.grdCashFlowSummary.ReadOnly = true;
            this.grdCashFlowSummary.ShowGroupPanel = false;
            // 
            // btnPrint
            // 
            resources.ApplyResources(this.btnPrint, "btnPrint");
            this.btnPrint.Items.AddRange(new Telerik.WinControls.RadItem[] {
            this.btnPrint_Summary,
            this.btnPrint_CashAndBank,
            this.btnPrint_CashFlowEntries});
            this.btnPrint.Name = "btnPrint";
            // 
            // btnPrint_Summary
            // 
            this.btnPrint_Summary.Name = "btnPrint_Summary";
            resources.ApplyResources(this.btnPrint_Summary, "btnPrint_Summary");
            this.btnPrint_Summary.Click += new System.EventHandler(this.BtnPrint_Summary_Click);
            // 
            // btnPrint_CashAndBank
            // 
            this.btnPrint_CashAndBank.Name = "btnPrint_CashAndBank";
            resources.ApplyResources(this.btnPrint_CashAndBank, "btnPrint_CashAndBank");
            this.btnPrint_CashAndBank.Click += new System.EventHandler(this.BtnPrint_CashAndBank_Click);
            // 
            // btnPrint_CashFlowEntries
            // 
            this.btnPrint_CashFlowEntries.Name = "btnPrint_CashFlowEntries";
            resources.ApplyResources(this.btnPrint_CashFlowEntries, "btnPrint_CashFlowEntries");
            this.btnPrint_CashFlowEntries.Click += new System.EventHandler(this.BtnPrint_CashFlowEntries_Click);
            // 
            // grpCFEntries
            // 
            this.grpCFEntries.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            resources.ApplyResources(this.grpCFEntries, "grpCFEntries");
            this.grpCFEntries.Controls.Add(this.vlSCTRAN);
            this.grpCFEntries.Name = "grpCFEntries";
            // 
            // vlSCTRAN
            // 
            resources.ApplyResources(this.vlSCTRAN, "vlSCTRAN");
            this.vlSCTRAN.Name = "vlSCTRAN";
            this.vlSCTRAN.OcxState = ((System.Windows.Forms.AxHost.State)(resources.GetObject("vlSCTRAN.OcxState")));
            this.vlSCTRAN.OnSetCustomItemData += new AxAccpacFldList._IAccpacViewListEvents_OnSetCustomItemDataEventHandler(this.VlSCTRAN_OnSetCustomItemData);
            this.vlSCTRAN.OnStartEditCustomData += new AxAccpacFldList._IAccpacViewListEvents_OnStartEditCustomDataEventHandler(this.VlSCTRAN_OnStartEditCustomData);
            this.vlSCTRAN.OnEndEdit += new AxAccpacFldList._IAccpacViewListEvents_OnEndEditEventHandler(this.VlSCTRAN_OnEndEdit);
            this.vlSCTRAN.SizeChanged += new System.EventHandler(this.VlSCTRAN_SizeChanged);
            // 
            // SCPageCashFlowSummary
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.grpCFEntries);
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.grdCashFlowSummary);
            this.Name = "SCPageCashFlowSummary";
            this.Load += new System.EventHandler(this.SCPageCashFlowSummary_Load);
            ((System.ComponentModel.ISupportInitialize)(this.grdCashFlowSummary.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdCashFlowSummary)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnPrint)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grpCFEntries)).EndInit();
            this.grpCFEntries.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.vlSCTRAN)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Telerik.WinControls.UI.RadGridView grdCashFlowSummary;
        private Telerik.WinControls.UI.RadDropDownButton btnPrint;
        private Telerik.WinControls.UI.RadMenuItem btnPrint_Summary;
        private Telerik.WinControls.UI.RadMenuItem btnPrint_CashAndBank;
        private Telerik.WinControls.UI.RadMenuItem btnPrint_CashFlowEntries;
        private Telerik.WinControls.UI.RadGroupBox grpCFEntries;
        private AxAccpacFldList.AxAccpacViewList vlSCTRAN;
    }
}
