namespace Sage.CA.SBS.ERP.Sage300.SC.AccpacSC1100.Pages
{
    partial class SCPayeeSummary
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SCPayeeSummary));
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn5 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn2 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn3 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition1 = new Telerik.WinControls.UI.TableViewDefinition();
            Telerik.WinControls.UI.CartesianArea cartesianArea1 = new Telerik.WinControls.UI.CartesianArea();
            Telerik.WinControls.UI.CategoricalAxis categoricalAxis1 = new Telerik.WinControls.UI.CategoricalAxis();
            Telerik.WinControls.UI.LinearAxis linearAxis1 = new Telerik.WinControls.UI.LinearAxis();
            Telerik.WinControls.UI.BarSeries barSeries1 = new Telerik.WinControls.UI.BarSeries();
            this.grdPayeeSummary = new Telerik.WinControls.UI.RadGridView();
            this.chtPayeeSummary = new Telerik.WinControls.UI.RadChartView();
            this.applicationDataBindingSource = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.grdPayeeSummary)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdPayeeSummary.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chtPayeeSummary)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.applicationDataBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // grdPayeeSummary
            // 
            resources.ApplyResources(this.grdPayeeSummary, "grdPayeeSummary");
            this.grdPayeeSummary.BackColor = System.Drawing.SystemColors.Control;
            this.grdPayeeSummary.Cursor = System.Windows.Forms.Cursors.Default;
            this.grdPayeeSummary.ForeColor = System.Drawing.SystemColors.ControlText;
            // 
            // 
            // 
            this.grdPayeeSummary.MasterTemplate.AllowColumnReorder = false;
            this.grdPayeeSummary.MasterTemplate.AllowRowResize = false;
            this.grdPayeeSummary.MasterTemplate.AutoGenerateColumns = false;
            this.grdPayeeSummary.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill;
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "Ranking";
            resources.ApplyResources(gridViewTextBoxColumn1, "gridViewTextBoxColumn1");
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "Ranking";
            gridViewTextBoxColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            gridViewTextBoxColumn1.Width = 72;
            gridViewTextBoxColumn2.EnableExpressionEditor = false;
            gridViewTextBoxColumn2.FieldName = "PayeeNumber";
            resources.ApplyResources(gridViewTextBoxColumn2, "gridViewTextBoxColumn2");
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "PayeeNumber";
            gridViewTextBoxColumn2.Width = 131;
            gridViewTextBoxColumn3.EnableExpressionEditor = false;
            gridViewTextBoxColumn3.FieldName = "Name";
            resources.ApplyResources(gridViewTextBoxColumn3, "gridViewTextBoxColumn3");
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "Name";
            gridViewTextBoxColumn3.Width = 159;
            gridViewTextBoxColumn4.EnableExpressionEditor = false;
            gridViewTextBoxColumn4.FieldName = "CurrencyCode";
            resources.ApplyResources(gridViewTextBoxColumn4, "gridViewTextBoxColumn4");
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.IsVisible = false;
            gridViewTextBoxColumn4.Name = "CurrencyCode";
            gridViewTextBoxColumn4.Width = 87;
            gridViewDecimalColumn1.EnableExpressionEditor = false;
            gridViewDecimalColumn1.FieldName = "CreditLimit";
            resources.ApplyResources(gridViewDecimalColumn1, "gridViewDecimalColumn1");
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.Name = "CreditLimit";
            gridViewDecimalColumn1.Width = 76;
            gridViewTextBoxColumn5.EnableExpressionEditor = false;
            gridViewTextBoxColumn5.FieldName = "CreditLimitString";
            resources.ApplyResources(gridViewTextBoxColumn5, "gridViewTextBoxColumn5");
            gridViewTextBoxColumn5.IsAutoGenerated = true;
            gridViewTextBoxColumn5.Name = "CreditLimitString";
            gridViewTextBoxColumn5.ReadOnly = true;
            gridViewTextBoxColumn5.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewTextBoxColumn5.Width = 145;
            gridViewDecimalColumn2.EnableExpressionEditor = false;
            gridViewDecimalColumn2.FieldName = "HighestBalance";
            resources.ApplyResources(gridViewDecimalColumn2, "gridViewDecimalColumn2");
            gridViewDecimalColumn2.IsAutoGenerated = true;
            gridViewDecimalColumn2.Name = "HighestBalance";
            gridViewDecimalColumn2.Width = 146;
            gridViewDecimalColumn3.EnableExpressionEditor = false;
            gridViewDecimalColumn3.FieldName = "OutstandingBalance";
            resources.ApplyResources(gridViewDecimalColumn3, "gridViewDecimalColumn3");
            gridViewDecimalColumn3.IsAutoGenerated = true;
            gridViewDecimalColumn3.Name = "OutstandingBalance";
            gridViewDecimalColumn3.Width = 145;
            this.grdPayeeSummary.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewTextBoxColumn4,
            gridViewDecimalColumn1,
            gridViewTextBoxColumn5,
            gridViewDecimalColumn2,
            gridViewDecimalColumn3});
            this.grdPayeeSummary.MasterTemplate.EnableAlternatingRowColor = true;
            this.grdPayeeSummary.MasterTemplate.EnableGrouping = false;
            this.grdPayeeSummary.MasterTemplate.EnableSorting = false;
            this.grdPayeeSummary.MasterTemplate.ShowRowHeaderColumn = false;
            this.grdPayeeSummary.MasterTemplate.ViewDefinition = tableViewDefinition1;
            this.grdPayeeSummary.Name = "grdPayeeSummary";
            this.grdPayeeSummary.ReadOnly = true;
            this.grdPayeeSummary.ShowGroupPanel = false;
            // 
            // chtPayeeSummary
            // 
            resources.ApplyResources(this.chtPayeeSummary, "chtPayeeSummary");
            this.chtPayeeSummary.AreaDesign = cartesianArea1;
            categoricalAxis1.AxisType = Telerik.Charting.AxisType.Second;
            categoricalAxis1.IsInverse = true;
            categoricalAxis1.IsPrimary = true;
            categoricalAxis1.LabelRotationAngle = 300D;
            categoricalAxis1.Title = "";
            linearAxis1.IsPrimary = true;
            linearAxis1.LabelFitMode = Telerik.Charting.AxisLabelFitMode.MultiLine;
            linearAxis1.LabelRotationAngle = 300D;
            linearAxis1.TickOrigin = null;
            linearAxis1.Title = "";
            this.chtPayeeSummary.Axes.AddRange(new Telerik.WinControls.UI.Axis[] {
            categoricalAxis1,
            linearAxis1});
            this.chtPayeeSummary.DataSource = this.applicationDataBindingSource;
            this.chtPayeeSummary.Name = "chtPayeeSummary";
            barSeries1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(196)))), ((int)(((byte)(65)))));
            barSeries1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(196)))), ((int)(((byte)(65)))));
            barSeries1.CategoryMember = "PayeeNumber";
            barSeries1.DataMember = "APSummary";
            barSeries1.DataSource = typeof(Sage.CA.SBS.ERP.Sage300.SC.Data.ApplicationData);
            barSeries1.HorizontalAxis = categoricalAxis1;
            barSeries1.LabelMode = Telerik.WinControls.UI.BarLabelModes.Top;
            barSeries1.ShowLabels = true;
            barSeries1.ValueMember = "OutstandingBalance";
            barSeries1.VerticalAxis = linearAxis1;
            this.chtPayeeSummary.Series.AddRange(new Telerik.WinControls.UI.ChartSeries[] {
            barSeries1});
            this.chtPayeeSummary.ShowGrid = false;
            this.chtPayeeSummary.LabelFormatting += new Telerik.WinControls.UI.ChartViewLabelFormattingEventHandler(this.ChtPayeeSummary_LabelFormatting);
            // 
            // applicationDataBindingSource
            // 
            this.applicationDataBindingSource.DataSource = typeof(Sage.CA.SBS.ERP.Sage300.SC.Data.ApplicationData);
            // 
            // SCPayeeSummary
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.grdPayeeSummary);
            this.Controls.Add(this.chtPayeeSummary);
            this.Name = "SCPayeeSummary";
            ((System.ComponentModel.ISupportInitialize)(this.grdPayeeSummary.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdPayeeSummary)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chtPayeeSummary)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.applicationDataBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Telerik.WinControls.UI.RadGridView grdPayeeSummary;
        private Telerik.WinControls.UI.RadChartView chtPayeeSummary;
        private System.Windows.Forms.BindingSource applicationDataBindingSource;
    }
}
