//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.SC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.SC.Resources.MenuResx", typeof(MenuResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C.
        /// </summary>
        public static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CashView.
        /// </summary>
        public static string SC0000 {
            get {
                return ResourceManager.GetString("SC0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C Inquiry.
        /// </summary>
        public static string SC1000 {
            get {
                return ResourceManager.GetString("SC1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string SC1101 {
            get {
                return ResourceManager.GetString("SC1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Summary.
        /// </summary>
        public static string SC1102 {
            get {
                return ResourceManager.GetString("SC1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/R Summary.
        /// </summary>
        public static string SC1103 {
            get {
                return ResourceManager.GetString("SC1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/P Summary.
        /// </summary>
        public static string SC1104 {
            get {
                return ResourceManager.GetString("SC1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        public static string SC1105 {
            get {
                return ResourceManager.GetString("SC1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C Setup.
        /// </summary>
        public static string SC9000 {
            get {
                return ResourceManager.GetString("SC9000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string SC9100 {
            get {
                return ResourceManager.GetString("SC9100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C.
        /// </summary>
        public static string SCModuleName {
            get {
                return ResourceManager.GetString("SCModuleName", resourceCulture);
            }
        }
    }
}
