//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms.DashboardResx", typeof(DashboardResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Receivable Collections.
        /// </summary>
        public static string ARC {
            get {
                return ResourceManager.GetString("ARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Balance.
        /// </summary>
        public static string CashEndingBalance {
            get {
                return ResourceManager.GetString("CashEndingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow.
        /// </summary>
        public static string CashFlow {
            get {
                return ResourceManager.GetString("CashFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash In.
        /// </summary>
        public static string CashIn {
            get {
                return ResourceManager.GetString("CashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Out.
        /// </summary>
        public static string CashOut {
            get {
                return ResourceManager.GetString("CashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Conversion Cycle.
        /// </summary>
        public static string CCC {
            get {
                return ResourceManager.GetString("CCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Ratio.
        /// </summary>
        public static string CurrentRatio {
            get {
                return ResourceManager.GetString("CurrentRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Payables Outstanding.
        /// </summary>
        public static string DPO {
            get {
                return ResourceManager.GetString("DPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Sales Outstanding.
        /// </summary>
        public static string DSO {
            get {
                return ResourceManager.GetString("DSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C Dashboard.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C Dashboard.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Cash From Operations.
        /// </summary>
        public static string NetOperations {
            get {
                return ResourceManager.GetString("NetOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Ratio.
        /// </summary>
        public static string QuickRatio {
            get {
                return ResourceManager.GetString("QuickRatio", resourceCulture);
            }
        }
    }
}
