//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoanResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoanResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms.LoanResx", typeof(LoanResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 3.
        /// </summary>
        public static string Address3 {
            get {
                return ResourceManager.GetString("Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 4.
        /// </summary>
        public static string Address4 {
            get {
                return ResourceManager.GetString("Address4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to the terms and conditions..
        /// </summary>
        public static string AgreeTermsAndConditions {
            get {
                return ResourceManager.GetString("AgreeTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Cap Amount.
        /// </summary>
        public static string AmountOffer {
            get {
                return ResourceManager.GetString("AmountOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Requested.
        /// </summary>
        public static string AmountRequest {
            get {
                return ResourceManager.GetString("AmountRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRN.
        /// </summary>
        public static string BRN {
            get {
                return ResourceManager.GetString("BRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Request has been canceled..
        /// </summary>
        public static string CancelSuccessMessage {
            get {
                return ResourceManager.GetString("CancelSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to set Loan Request status to Approved?.
        /// </summary>
        public static string ConfirmationApproved {
            get {
                return ResourceManager.GetString("ConfirmationApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel Loan Request?.
        /// </summary>
        public static string ConfirmationCancel {
            get {
                return ResourceManager.GetString("ConfirmationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to set Loan Request status to Rejected?.
        /// </summary>
        public static string ConfirmationRejected {
            get {
                return ResourceManager.GetString("ConfirmationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to re-submit Loan Request?.
        /// </summary>
        public static string ConfirmationResubmit {
            get {
                return ResourceManager.GetString("ConfirmationResubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to submit Loan Request?.
        /// </summary>
        public static string ConfirmationSubmit {
            get {
                return ResourceManager.GetString("ConfirmationSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Offered.
        /// </summary>
        public static string DateOffered {
            get {
                return ResourceManager.GetString("DateOffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Submitted.
        /// </summary>
        public static string DateSubmitted {
            get {
                return ResourceManager.GetString("DateSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        public static string EmailCC {
            get {
                return ResourceManager.GetString("EmailCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string EmailFrom {
            get {
                return ResourceManager.GetString("EmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Submission Details.
        /// </summary>
        public static string EmailSubmissionDetails {
            get {
                return ResourceManager.GetString("EmailSubmissionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Submitted.
        /// </summary>
        public static string EmailSubmitted {
            get {
                return ResourceManager.GetString("EmailSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string EmailTo {
            get {
                return ResourceManager.GetString("EmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C Loan.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C Loan.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Activities.
        /// </summary>
        public static string LoanActivities {
            get {
                return ResourceManager.GetString("LoanActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Number.
        /// </summary>
        public static string LoanNumber {
            get {
                return ResourceManager.GetString("LoanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Request Details.
        /// </summary>
        public static string LoanRequestDetails {
            get {
                return ResourceManager.GetString("LoanRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Comments.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resubmit.
        /// </summary>
        public static string Resubmit {
            get {
                return ResourceManager.GetString("Resubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Request has been resubmitted successfully..
        /// </summary>
        public static string ResubmitSuccessMessage {
            get {
                return ResourceManager.GetString("ResubmitSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Update.
        /// </summary>
        public static string StatusUpdate {
            get {
                return ResourceManager.GetString("StatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Only the information shown in this screen is transmitted to Standard Chartered. A copy of this email will also be sent to the recipients in the CC list..
        /// </summary>
        public static string SubmissionNote {
            get {
                return ResourceManager.GetString("SubmissionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Request has been submitted successfully..
        /// </summary>
        public static string SubmitSuccessMessage {
            get {
                return ResourceManager.GetString("SubmitSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string UpdateApproved {
            get {
                return ResourceManager.GetString("UpdateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UpdateCancel {
            get {
                return ResourceManager.GetString("UpdateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string UpdateRejected {
            get {
                return ResourceManager.GetString("UpdateRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Submitted.
        /// </summary>
        public static string UserSubmitted {
            get {
                return ResourceManager.GetString("UserSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Terms and Conditions.
        /// </summary>
        public static string ViewTermsAndConditions {
            get {
                return ResourceManager.GetString("ViewTermsAndConditions", resourceCulture);
            }
        }
    }
}
