//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OptionsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms.OptionsResx", typeof(OptionsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Reg. No..
        /// </summary>
        public static string BRN {
            get {
                return ResourceManager.GetString("BRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Reg. Year.
        /// </summary>
        public static string BRYear {
            get {
                return ResourceManager.GetString("BRYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Reg. Year (Calc.).
        /// </summary>
        public static string BRYearCalculated {
            get {
                return ResourceManager.GetString("BRYearCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Date.
        /// </summary>
        public static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Period.
        /// </summary>
        public static string CurrentPeriod {
            get {
                return ResourceManager.GetString("CurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year.
        /// </summary>
        public static string CurrentYear {
            get {
                return ResourceManager.GetString("CurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Forecast Entry Number.
        /// </summary>
        public static string DefaultForecastNumber {
            get {
                return ResourceManager.GetString("DefaultForecastNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy.
        /// </summary>
        public static string Dummy {
            get {
                return ResourceManager.GetString("Dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender&apos;s Email.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVISORY.
        /// </summary>
        public static string EmailAdvisory {
            get {
                return ResourceManager.GetString("EmailAdvisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email setting here is used to support email notifications when cash flow thresholds are breached. When such situations arise, email notifications will be sent out. Emails will contain sensitive and confidential information about your cash flow status. You should take extra care in choosing the right people to receive the notifications..
        /// </summary>
        public static string EmailAdvisoryText {
            get {
                return ResourceManager.GetString("EmailAdvisoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Email for Notification.
        /// </summary>
        public static string EmailAlert {
            get {
                return ResourceManager.GetString("EmailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        public static string EmailHost {
            get {
                return ResourceManager.GetString("EmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to receiving promotional materials from Sage and other third-party companies via email, in accordance with the Personal Data Protection Act 2012 and our data protection policy (available at our website). Please note that all communications sent to you will be through Sage..
        /// </summary>
        public static string EmailOffer {
            get {
                return ResourceManager.GetString("EmailOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string EmailPassword {
            get {
                return ResourceManager.GetString("EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string EmailPasswordString {
            get {
                return ResourceManager.GetString("EmailPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Port.
        /// </summary>
        public static string EmailPort {
            get {
                return ResourceManager.GetString("EmailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Test Email.
        /// </summary>
        public static string EmailSendTest {
            get {
                return ResourceManager.GetString("EmailSendTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze Email Until.
        /// </summary>
        public static string EmailSnoozeUntil {
            get {
                return ResourceManager.GetString("EmailSnoozeUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        public static string EmailSSL {
            get {
                return ResourceManager.GetString("EmailSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string EmailTest {
            get {
                return ResourceManager.GetString("EmailTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send Test email.\nPlease verify your settings..
        /// </summary>
        public static string EmailTestFailed {
            get {
                return ResourceManager.GetString("EmailTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test email sent successfully. Please check your inbox..
        /// </summary>
        public static string EmailTestSuccessed {
            get {
                return ResourceManager.GetString("EmailTestSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients&apos; Emails.
        /// </summary>
        public static string EmailTo {
            get {
                return ResourceManager.GetString("EmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string EmailUser {
            get {
                return ResourceManager.GetString("EmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C Options.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string EntityTypeAU {
            get {
                return ResourceManager.GetString("EntityTypeAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string EntityTypeHK {
            get {
                return ResourceManager.GetString("EntityTypeHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string EntityTypeMY {
            get {
                return ResourceManager.GetString("EntityTypeMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string EntityTypeNZ {
            get {
                return ResourceManager.GetString("EntityTypeNZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string EntityTypeSG {
            get {
                return ResourceManager.GetString("EntityTypeSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Entry.
        /// </summary>
        public static string FE {
            get {
                return ResourceManager.GetString("FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Forecast Number.
        /// </summary>
        public static string FEDocumentDefault {
            get {
                return ResourceManager.GetString("FEDocumentDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Forecast Number.
        /// </summary>
        public static string FEDocumentNext {
            get {
                return ResourceManager.GetString("FEDocumentNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Entry Number Length.
        /// </summary>
        public static string FELength {
            get {
                return ResourceManager.GetString("FELength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Entry Next Number.
        /// </summary>
        public static string FENextNumber {
            get {
                return ResourceManager.GetString("FENextNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Entry Prefix.
        /// </summary>
        public static string FEPrefix {
            get {
                return ResourceManager.GetString("FEPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Currency.
        /// </summary>
        public static string FunctionalCurrency {
            get {
                return ResourceManager.GetString("FunctionalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Pending A/P Transactions.
        /// </summary>
        public static string IncludePendingAP {
            get {
                return ResourceManager.GetString("IncludePendingAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Pending A/R Transactions.
        /// </summary>
        public static string IncludePendingAR {
            get {
                return ResourceManager.GetString("IncludePendingAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Pending G/L Transactions.
        /// </summary>
        public static string IncludePendingGL {
            get {
                return ResourceManager.GetString("IncludePendingGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string IndustryAU {
            get {
                return ResourceManager.GetString("IndustryAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string IndustryHK {
            get {
                return ResourceManager.GetString("IndustryHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string IndustryMY {
            get {
                return ResourceManager.GetString("IndustryMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string IndustryNZ {
            get {
                return ResourceManager.GetString("IndustryNZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string IndustrySG {
            get {
                return ResourceManager.GetString("IndustrySG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Processed Date.
        /// </summary>
        public static string LastProcessedDate {
            get {
                return ResourceManager.GetString("LastProcessedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Processed Time.
        /// </summary>
        public static string LastProcessedTime {
            get {
                return ResourceManager.GetString("LastProcessedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Forecast Entry Number.
        /// </summary>
        public static string NextForecastNumber {
            get {
                return ResourceManager.GetString("NextForecastNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Number.
        /// </summary>
        public static string NextNumber {
            get {
                return ResourceManager.GetString("NextNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 1 End.
        /// </summary>
        public static string Period1End {
            get {
                return ResourceManager.GetString("Period1End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 1 Start.
        /// </summary>
        public static string Period1Start {
            get {
                return ResourceManager.GetString("Period1Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 2 End.
        /// </summary>
        public static string Period2End {
            get {
                return ResourceManager.GetString("Period2End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 2 Start.
        /// </summary>
        public static string Period2Start {
            get {
                return ResourceManager.GetString("Period2Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 3 End.
        /// </summary>
        public static string Period3End {
            get {
                return ResourceManager.GetString("Period3End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 3 Start.
        /// </summary>
        public static string Period3Start {
            get {
                return ResourceManager.GetString("Period3Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 4 End.
        /// </summary>
        public static string Period4End {
            get {
                return ResourceManager.GetString("Period4End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 4 Start.
        /// </summary>
        public static string Period4Start {
            get {
                return ResourceManager.GetString("Period4Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 5 End.
        /// </summary>
        public static string Period5End {
            get {
                return ResourceManager.GetString("Period5End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 5 Start.
        /// </summary>
        public static string Period5Start {
            get {
                return ResourceManager.GetString("Period5Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 6 End.
        /// </summary>
        public static string Period6End {
            get {
                return ResourceManager.GetString("Period6End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 6 Start.
        /// </summary>
        public static string Period6Start {
            get {
                return ResourceManager.GetString("Period6Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessCommand.
        /// </summary>
        public static string ProcessCommand {
            get {
                return ResourceManager.GetString("ProcessCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Numbers.
        /// </summary>
        public static string ProcessingDocumentNumbers {
            get {
                return ResourceManager.GetString("ProcessingDocumentNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Periods.
        /// </summary>
        public static string ProcessingForecastPeriod {
            get {
                return ResourceManager.GetString("ProcessingForecastPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ProcessingSettings {
            get {
                return ResourceManager.GetString("ProcessingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string ProcessingStatistics {
            get {
                return ResourceManager.GetString("ProcessingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateDate.
        /// </summary>
        public static string RateDate {
            get {
                return ResourceManager.GetString("RateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Operator.
        /// </summary>
        public static string RateOperator {
            get {
                return ResourceManager.GetString("RateOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportingCurrency.
        /// </summary>
        public static string ReportingCurrency {
            get {
                return ResourceManager.GetString("ReportingCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string TabAccounts {
            get {
                return ResourceManager.GetString("TabAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string TabCompany {
            get {
                return ResourceManager.GetString("TabCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TabEmail {
            get {
                return ResourceManager.GetString("TabEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string TabProcessing {
            get {
                return ResourceManager.GetString("TabProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        public static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
    }
}
