//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PayeeSummaryResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PayeeSummaryResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms.PayeeSummaryResx", typeof(PayeeSummaryResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit.
        /// </summary>
        public static string CreditLimit {
            get {
                return ResourceManager.GetString("CreditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit.
        /// </summary>
        public static string CreditLimitString {
            get {
                return ResourceManager.GetString("CreditLimitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer #.
        /// </summary>
        public static string CustomerNumber {
            get {
                return ResourceManager.GetString("CustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C Payee Summary.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C A/P Summary - Top 10 Outstanding Balance.
        /// </summary>
        public static string EntityAP {
            get {
                return ResourceManager.GetString("EntityAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C A/R Summary - Top 10 Outstanding Balance.
        /// </summary>
        public static string EntityAR {
            get {
                return ResourceManager.GetString("EntityAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Balance.
        /// </summary>
        public static string HighestBalance {
            get {
                return ResourceManager.GetString("HighestBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding Balance.
        /// </summary>
        public static string OutstandingBalance {
            get {
                return ResourceManager.GetString("OutstandingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayeeNumber.
        /// </summary>
        public static string PayeeNumber {
            get {
                return ResourceManager.GetString("PayeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Payables Forecast.
        /// </summary>
        public static string PrintPayablesForecast {
            get {
                return ResourceManager.GetString("PrintPayablesForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Receivables Forecast.
        /// </summary>
        public static string PrintReceivablesForecast {
            get {
                return ResourceManager.GetString("PrintReceivablesForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Top 10 Customers Outstanding.
        /// </summary>
        public static string PrintTop10CustomersOutstanding {
            get {
                return ResourceManager.GetString("PrintTop10CustomersOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Top 10 Vendors Outstanding.
        /// </summary>
        public static string PrintTop10VendorsOutstanding {
            get {
                return ResourceManager.GetString("PrintTop10VendorsOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor #.
        /// </summary>
        public static string VendorNumber {
            get {
                return ResourceManager.GetString("VendorNumber", resourceCulture);
            }
        }
    }
}
