//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SummaryResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SummaryResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.SC.Resources.Forms.SummaryResx", typeof(SummaryResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string AmountPeriod0 {
            get {
                return ResourceManager.GetString("AmountPeriod0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - 30.
        /// </summary>
        public static string AmountPeriod1 {
            get {
                return ResourceManager.GetString("AmountPeriod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31 - 60.
        /// </summary>
        public static string AmountPeriod2 {
            get {
                return ResourceManager.GetString("AmountPeriod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 61 - 90.
        /// </summary>
        public static string AmountPeriod3 {
            get {
                return ResourceManager.GetString("AmountPeriod3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 91 - 120.
        /// </summary>
        public static string AmountPeriod4 {
            get {
                return ResourceManager.GetString("AmountPeriod4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121 - 150.
        /// </summary>
        public static string AmountPeriod5 {
            get {
                return ResourceManager.GetString("AmountPeriod5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 150.
        /// </summary>
        public static string AmountPeriod6 {
            get {
                return ResourceManager.GetString("AmountPeriod6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string AmountTotal {
            get {
                return ResourceManager.GetString("AmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/C Cash Flow Summary.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Activities Entry.
        /// </summary>
        public static string OtherActivitiesEntry {
            get {
                return ResourceManager.GetString("OtherActivitiesEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Cash and Bank Accounts.
        /// </summary>
        public static string PrintCashAndBankAccount {
            get {
                return ResourceManager.GetString("PrintCashAndBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Cash Flow Summary.
        /// </summary>
        public static string PrintCashFlowSummary {
            get {
                return ResourceManager.GetString("PrintCashFlowSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Inflow and Outflow Entries.
        /// </summary>
        public static string PrintInflowAndOutflowEntries {
            get {
                return ResourceManager.GetString("PrintInflowAndOutflowEntries", resourceCulture);
            }
        }
    }
}
